In [1]:
import sys
import os
os.getcwd()

'/Users/rraymondhp/Downloads/NewMBP/202305KoyasuFraxis'

In [2]:
!pip install -U qiskit-ibm-runtime

In [3]:
!pip install -U qiskit-ibm-provider

In [4]:
!pip install scikit-learn

In [5]:
import sys
sys.path.append('/Users/rraymondhp/Downloads/NewMBP/202305KoyasuFraxis')
import os
from training_molecules import parallel_train
import time
import numpy as np

In [6]:
from qiskit_ibm_runtime import QiskitRuntimeService

# Save your credentials on disk.
#QiskitRuntimeService.save_account(channel='ibm_quantum', token="24dd9c19c7cd0fdd2d43d0067893c68c0b5071603ce40c22b3c0c8c04af923f0d276472ad3ffd19e3478c84902f574d79d358c0ae698d79abf876053709b1eb8")

service = QiskitRuntimeService(
    channel='ibm_quantum',
    instance='ibm-q-utokyo/internal/hirashi-jst',
)

#service = QiskitRuntimeService(
#    channel='ibm_quantum',
#    instance='ibm-q-utokyo/internal/cs-slecture8',
#)

In [7]:
Q = 2 #number of qubits
L = 2 #number of fraxis layer
W = 100#number of quantum node
N = 100 #number of training data size
M = 3600 #number of testing data size
U = 2  #number of update
atomNo = 45
#backend = service.backend('ibm_kawasaki')
#backend = service.backend('simulator_mps')
backend = service.backend('ibm_seattle')
params = np.zeros((L, Q, 3))+np.array([0., 0., 1.])

In [ ]:
if __name__ == '__main__':
    st = time.time()
    parallel_train(Q, L, W, N, M, U, service, backend, params, isScaled=False, atomNo=atomNo)        
    print('Implementation time : ', time.time()-st)

Start loading data
AFTER ARRAYING
(100, 25) (3600, 25) (3600,) (100,)
End loading data
B4 TRANSPILE
AF TRANSPILE
30.503556909686264
ACC_train:  68.0 
SCORE_train:  18.81299999999963
[[[ 0.15468559  0.76002565 -0.63121579]
  [ 0.          0.          1.        ]]

 [[ 0.          0.          1.        ]
  [ 0.          0.          1.        ]]]
B4 TRANSPILE
AF TRANSPILE
15.543813880141569
ACC_train:  57.0 
SCORE_train:  11.029999999999847
[[[ 0.15468559  0.76002565 -0.63121579]
  [ 0.63310766  0.39336981  0.6666595 ]]

 [[ 0.          0.          1.        ]
  [ 0.          0.          1.        ]]]
B4 TRANSPILE
AF TRANSPILE
24.566154551925475
ACC_train:  58.0 
SCORE_train:  14.576999999999277
[[[ 0.15468559  0.76002565 -0.63121579]
  [ 0.63310766  0.39336981  0.6666595 ]]

 [[ 0.12015317  0.4563881   0.88163094]
  [ 0.          0.          1.        ]]]
B4 TRANSPILE
AF TRANSPILE
13.547036649069984
ACC_train:  55.0 
SCORE_train:  4.317999999999846
[[[ 0.15468559  0.76002565 -0.63121579]

In [ ]:
%tb

In [ ]:
import qiskit
qiskit.__qiskit_version__