In [1]:
import sys
import os
os.getcwd()

'/home/jovyan/koyasu_fraxis'

In [2]:
import sys
sys.path.append('/home/jovyan/koyasu_fraxis')
import os
from training import parallel_train
import time
import numpy as np

<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject


In [3]:
#from qiskit.providers.ibmq import IBMQ
#from qiskit.providers.aer import AerSimulator

# get a real backend from a real provider
#provider = IBMQ.load_account()
#backend = provider.get_backend('ibm_auckland')

# generate a simulator that mimics the real quantum system with the latest calibration results
#backend_sim = AerSimulator.from_backend(backend)

from qiskit_ibm_runtime import QiskitRuntimeService

# Save your credentials on disk.
# QiskitRuntimeService.save_account(channel='ibm_quantum', token=<IBM Quantum API key>)

service = QiskitRuntimeService(
    channel='ibm_quantum',
    instance='ibm-q-utokyo/internal/hirashi-jst',
)

#service = QiskitRuntimeService(
#    channel='ibm_quantum',
#    instance='ibm-q-utokyo/internal/cs-slecture8',
#)

In [4]:
Q = 5 #number of qubits
L = 3 #number of fraxis layer
W = 10 #number of quantum node
N = 100 #number of training data size
M = 100 #number of testing data size
U = 2  #number of update
backend = service.backend('simulator_mps')
params = np.zeros((L, Q, 3))+np.array([0, 0, 1])

In [5]:
if __name__ == '__main__':
    st = time.time()
    parallel_train(Q, L, W, N, M, U, service, backend, params)        
    print('Implementation time : ', time.time()-st)

51.696126557051784
ACC_train:  69.0 
SCORE_train:  51.95399999999997
ACC_test:  65.0 
SCORE_test:  35.963
[[[-0.19077749  0.9601571   0.20421139]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]]

 [[ 0.          0.          1.        ]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]]

 [[ 0.          0.          1.        ]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]]]
52.84340844389732
ACC_train:  70.0 
SCORE_train:  52.60899999999998
ACC_test:  68.0 
SCORE_test:  38.923999999999985
[[[-0.19077749  0.9601571   0.20421139]
  [-0.13254834 -0.00161291  0.99117523]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]
  [ 0.     

In [6]:
%tb

RuntimeJobFailureError: 'Unable to retrieve job result. Job cg3h0ec091ptu0ca5si0 has failed:\n2023-03-07T10:21:17.447812404Z Setting up watches.\n2023-03-07T10:21:17.447873339Z Watches established.\n2023-03-07T10:21:19.191555219Z INFO:     Started server process [7]\n2023-03-07T10:21:19.191620222Z INFO:     Waiting for application startup.\n2023-03-07T10:21:19.192029635Z INFO:     Application startup complete.\n2023-03-07T10:21:19.194047681Z INFO:     Uvicorn running on http://127.0.0.1:8081 (Press CTRL+C to quit)\n'