In [1]:
import sys
import os
os.getcwd()

'/Users/rraymondhp/Downloads/NewMBP/202305KoyasuFraxis'

In [2]:
!pip install -U qiskit-ibm-runtime

In [3]:
!pip install -U qiskit-ibm-provider

In [4]:
!pip install scikit-learn

In [5]:
import sys
sys.path.append('/Users/rraymondhp/Downloads/NewMBP/202305KoyasuFraxis')
import os
from training_molecules import parallel_train
import time
import numpy as np

In [6]:
from qiskit_ibm_runtime import QiskitRuntimeService

# Save your credentials on disk.
#QiskitRuntimeService.save_account(channel='ibm_quantum', token="24dd9c19c7cd0fdd2d43d0067893c68c0b5071603ce40c22b3c0c8c04af923f0d276472ad3ffd19e3478c84902f574d79d358c0ae698d79abf876053709b1eb8")

service = QiskitRuntimeService(
    channel='ibm_quantum',
    instance='ibm-q-utokyo/internal/hirashi-jst',
)

#service = QiskitRuntimeService(
#    channel='ibm_quantum',
#    instance='ibm-q-utokyo/internal/cs-slecture8',
#)

In [7]:
Q = 3 #number of qubits
L = 3 #number of fraxis layer
W = 20#number of quantum node
N = 100 #number of training data size
M = 3600 #number of testing data size
U = 3  #number of update
atomNo = 45
#backend = service.backend('ibm_kawasaki')
backend = service.backend('simulator_mps')
#backend = service.backend('ibm_seattle')
params = np.zeros((L, Q, 3))+np.array([0., 0., 1.])

In [8]:
if __name__ == '__main__':
    st = time.time()
    parallel_train(Q, L, W, N, M, U, service, backend, params, isScaled=False, atomNo=atomNo)        
    print('Implementation time : ', time.time()-st)

Start loading data
AFTER ARRAYING
(100, 25) (3600, 25) (3600,) (100,)
End loading data
B4 TRANSPILE
AF TRANSPILE
B4 TRANSPILE
AF TRANSPILE
B4 TRANSPILE
AF TRANSPILE
B4 TRANSPILE
AF TRANSPILE
B4 TRANSPILE
AF TRANSPILE
17.482729300066328
ACC_train:  59.0 
SCORE_train:  17.38999999999935
[[[-0.2635437  -0.29884454 -0.91718954]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]]

 [[ 0.          0.          1.        ]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]]

 [[ 0.          0.          1.        ]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]]]
B4 TRANSPILE
AF TRANSPILE
B4 TRANSPILE
AF TRANSPILE
B4 TRANSPILE
AF TRANSPILE
B4 TRANSPILE
AF TRANSPILE
B4 TRANSPILE
AF TRANSPILE
19.03931546711027
ACC_train:  59.0 
SCORE_train:  19.136999999999162
[[[-0.2635437  -0.29884454 -0.91718954]
  [-0.33368062 -0.07403927  0.93977414]
  [ 0.          0.          1.        ]]

 [[ 0.          0.         

ACC_train:  71.0 
SCORE_train:  30.997999999999678
[[[ 0.14253976  0.59835727  0.78844847]
  [-0.25709242 -0.0688932   0.96392801]
  [-0.67288344 -0.3908546   0.62806095]]

 [[-0.0163787  -0.63089995  0.7756913 ]
  [-0.29152221  0.03771503  0.95582026]
  [ 0.50071256 -0.83456877  0.22974313]]

 [[-0.01291724 -0.05313018  0.99850405]
  [ 0.78321871  0.55600395 -0.27825898]
  [-0.42331732 -0.68918836 -0.58806619]]]
B4 TRANSPILE
AF TRANSPILE
B4 TRANSPILE
AF TRANSPILE
B4 TRANSPILE
AF TRANSPILE
B4 TRANSPILE
AF TRANSPILE
B4 TRANSPILE
AF TRANSPILE
31.402248234098188
ACC_train:  72.0 
SCORE_train:  31.608999999999384
[[[ 0.14253976  0.59835727  0.78844847]
  [-0.25709242 -0.0688932   0.96392801]
  [-0.67288344 -0.3908546   0.62806095]]

 [[-0.0163787  -0.63089995  0.7756913 ]
  [-0.29152221  0.03771503  0.95582026]
  [ 0.50071256 -0.83456877  0.22974313]]

 [[-0.04886648 -0.10372859  0.99340447]
  [ 0.78321871  0.55600395 -0.27825898]
  [-0.42331732 -0.68918836 -0.58806619]]]
B4 TRANSPILE
AF T

In [9]:
%tb

No traceback available to show.
