In [1]:
import sys
import os
os.getcwd()

'/home/jovyan/koyasu_fraxis'

In [2]:
import sys
sys.path.append('/home/jovyan/koyasu_fraxis')
import os
from training import parallel_train
import time
import numpy as np

<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject


In [3]:
from qiskit_ibm_runtime import QiskitRuntimeService

# Save your credentials on disk.
# QiskitRuntimeService.save_account(channel='ibm_quantum', token=<IBM Quantum API key>)

service = QiskitRuntimeService(
    channel='ibm_quantum',
    instance='ibm-q-utokyo/internal/hirashi-jst',
)

#service = QiskitRuntimeService(
#    channel='ibm_quantum',
#    instance='ibm-q-utokyo/internal/cs-slecture8',
#)

In [4]:
Q = 5 #number of qubits
L = 1 #number of fraxis layer
W = 5 #number of quantum node
N = 100 #number of training data size
M = 100 #number of testing data size
U = 2  #number of update
backend = service.backend('ibm_kawasaki')
params = np.zeros((L, Q, 3))+np.array([0, 0, 1])

In [5]:
if __name__ == '__main__':
    st = time.time()
    parallel_train(Q, L, W, N, M, U, service, backend, params)        
    print('Implementation time : ', time.time()-st)

47.3838730812154
ACC_train:  74.0 
SCORE_train:  46.807005189446535
ACC_test:  76.0 
SCORE_test:  57.52271660795625
[[[-0.69671648  0.13627535 -0.70428345]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]]]
48.76246486730975
ACC_train:  76.0 
SCORE_train:  48.58407972191323
ACC_test:  79.0 
SCORE_test:  57.57669967649308
[[[-0.69671648  0.13627535 -0.70428345]
  [-0.51828385 -0.09631015 -0.84976832]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]]]
52.530302102172286
ACC_train:  79.0 
SCORE_train:  49.51224098005602
ACC_test:  78.0 
SCORE_test:  56.829950007975604
[[[-0.69671648  0.13627535 -0.70428345]
  [-0.51828385 -0.09631015 -0.84976832]
  [-0.57316334 -0.6200251  -0.53577296]
  [ 0.          0.          1.        ]
  [ 0.          0.          1.        ]]]
48.92318854659865
ACC_train:  78.0 
SCORE_tr

In [6]:
%tb

IBMRuntimeError: 'Failed to run program: \'400 Client Error: Bad Request for url: https://runtime-us-east.quantum-computing.ibm.com/jobs. {"errors":[{"code":"bad_request","message":"session closed: Session cg4nkavvd9sb5bf41390 has been closed","more_info":"https://cloud.ibm.com/apidocs/quantum-computing#error-handling"}],"trace":"cg4ulo7vd9sb5bf9t41g"}\''